# 图片验证码Redis有效期， 单位：秒
IMAGE_CODE_REDIS_EXPIRES = 300

# 短信验证码发送时间间隔
SMS_CODE_REDIS_INTERVAL = 60

# 短信验证码Redis有效期，单位：秒
SMS_CODE_REDIS_EXPIRES = 300

# 发送短信token的有效期
SEND_SMS_CODE_TOKEN_EXIPIRES = 300

# 修改密码token的有效期
SET_PASSWORD_TOKEN_EXPIRES = 300

# 绑定QQ用户的access_token有效期
SAVE_QQ_USER_TOKEN_EXPIRES = 600

# 邮箱验证token有效期
EMAIL_VERIFY_TOKEN_EXPIRES = 60 * 60 * 24

# 用户收货地址个数
USER_ADDRESS_COUNT_LIMIT = 20

USER_ADDRESS_COUNTS_LIMIT = 20

USER_BROWSING_HISTORY_COUNTS_LIMIT = 5

HOT_SKUS_COUNT_LIMIT = 2


# 七牛空间域名
QINIU_DOMIN_PREFIX = "http://p7os57adh.bkt.clouddn.com/"

